using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Architecture Description Lanaguage")]
[assembly: AssemblyDescription("This module is auto-generated by PAT")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Semantic Engineering Pte. Ltd.")]
[assembly: AssemblyProduct("PAT - An Enhanced Simulation and Model Checking Tool")]
[assembly: AssemblyCopyright("Copyright © Semantic Engineering Pte. Ltd. 2011")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("a250db08-7aa4-47ce-a47a-d7d1cd356a27")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]