//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAT.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PAT.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _04378 {
            get {
                object obj = ResourceManager.GetObject("_04378", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  column .
        /// </summary>
        internal static string _column_ {
            get {
                return ResourceManager.GetString("_column_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  running on .
        /// </summary>
        internal static string _running_on_ {
            get {
                return ResourceManager.GetString("_running_on_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while compiling the C# code: .
        /// </summary>
        internal static string An_error_occurred_while_compiling_the_C__code__ {
            get {
                return ResourceManager.GetString("An_error_occurred_while_compiling_the_C__code__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Zeno Check Selected.
        /// </summary>
        internal static string Apply_Zeno_Check_Selected {
            get {
                return ResourceManager.GetString("Apply_Zeno_Check_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Zeno Check UnSelected.
        /// </summary>
        internal static string Apply_Zeno_Check_UnSelected {
            get {
                return ResourceManager.GetString("Apply_Zeno_Check_UnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected process?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_the_selected_process_ {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_the_selected_process_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one process is needed in the model..
        /// </summary>
        internal static string At_least_one_process_is_needed_in_the_model_ {
            get {
                return ResourceManager.GetString("At_least_one_process_is_needed_in_the_model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDD Selected.
        /// </summary>
        internal static string BDD_Selected {
            get {
                return ResourceManager.GetString("BDD_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDD UnSelected.
        /// </summary>
        internal static string BDD_UnSelected {
            get {
                return ResourceManager.GetString("BDD_UnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# library code is saved successfully!.
        /// </summary>
        internal static string C__library_code_is_saved_successfully_ {
            get {
                return ResourceManager.GetString("C__library_code_is_saved_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# library is built successfully! You can use them now in your models..
        /// </summary>
        internal static string C__library_is_built_successfully__You_can_use_them_now_in_your_models_ {
            get {
                return ResourceManager.GetString("C__library_is_built_successfully__You_can_use_them_now_in_your_models_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking file:.
        /// </summary>
        internal static string Checking_file_ {
            get {
                return ResourceManager.GetString("Checking_file_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Clear {
            get {
                object obj = ResourceManager.GetObject("Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document .
        /// </summary>
        internal static string Document_ {
            get {
                return ResourceManager.GetString("Document_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document {0} unsaved. Do you want to save it before close?.
        /// </summary>
        internal static string Document__0__unsaved__Do_you_want_to_save_it_before_close_ {
            get {
                return ResourceManager.GetString("Document__0__unsaved__Do_you_want_to_save_it_before_close_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to open the folder of .
        /// </summary>
        internal static string Double_click_to_open_the_folder_of_ {
            get {
                return ResourceManager.GetString("Double_click_to_open_the_folder_of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Process Name.
        /// </summary>
        internal static string Duplicate_Process_Name {
            get {
                return ResourceManager.GetString("Duplicate_Process_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is sent successfully..
        /// </summary>
        internal static string Email_is_sent_successfully_ {
            get {
                return ResourceManager.GetString("Email_is_sent_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: file format is not supported!.
        /// </summary>
        internal static string Error__file_format_is_not_supported_ {
            get {
                return ResourceManager.GetString("Error__file_format_is_not_supported_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened in opening .
        /// </summary>
        internal static string Error_happened_in_opening_ {
            get {
                return ResourceManager.GetString("Error_happened_in_opening_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happned in loading module .
        /// </summary>
        internal static string Error_happned_in_loading_module_ {
            get {
                return ResourceManager.GetString("Error_happned_in_loading_module_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception happened: .
        /// </summary>
        internal static string Exception_happened__ {
            get {
                return ResourceManager.GetString("Exception_happened__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception happened during saving: .
        /// </summary>
        internal static string Exception_happened_during_saving__ {
            get {
                return ResourceManager.GetString("Exception_happened_during_saving__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception happened during the compilation: .
        /// </summary>
        internal static string Exception_happened_during_the_compilation__ {
            get {
                return ResourceManager.GetString("Exception_happened_during_the_compilation__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception happened during the Contracts compilation: .
        /// </summary>
        internal static string Exception_happened_during_the_Contracts_compilation__ {
            get {
                return ResourceManager.GetString("Exception_happened_during_the_Contracts_compilation__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format is not supported by PAT!.
        /// </summary>
        internal static string File_format_is_not_supported_by_PAT_ {
            get {
                return ResourceManager.GetString("File_format_is_not_supported_by_PAT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Counterexample Selected.
        /// </summary>
        internal static string Generate_Counterexample_Selected {
            get {
                return ResourceManager.GetString("Generate_Counterexample_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Counterexample UnSelected.
        /// </summary>
        internal static string Generate_Counterexample_UnSelected {
            get {
                return ResourceManager.GetString("Generate_Counterexample_UnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Result....
        /// </summary>
        internal static string Generating_Result___ {
            get {
                return ResourceManager.GetString("Generating_Result___", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap getAllTraces {
            get {
                object obj = ResourceManager.GetObject("getAllTraces", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar Checked.
        /// </summary>
        internal static string Grammar_Checked {
            get {
                return ResourceManager.GetString("Grammar_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        internal static string Invalid_email_address_ {
            get {
                return ResourceManager.GetString("Invalid_email_address_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name!.
        /// </summary>
        internal static string Invalid_name_ {
            get {
                return ResourceManager.GetString("Invalid_name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number.
        /// </summary>
        internal static string Line_number {
            get {
                return ResourceManager.GetString("Line_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading error.
        /// </summary>
        internal static string Loading_error {
            get {
                return ResourceManager.GetString("Loading_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No duplicated process names are allowed.
        /// </summary>
        internal static string No_duplicated_process_names_are_allowed {
            get {
                return ResourceManager.GetString("No_duplicated_process_names_are_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Mode Selected.
        /// </summary>
        internal static string Normal_Mode_Selected {
            get {
                return ResourceManager.GetString("Normal_Mode_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Error:.
        /// </summary>
        internal static string Open_Error_ {
            get {
                return ResourceManager.GetString("Open_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Error: the selected file is not found!.
        /// </summary>
        internal static string Open_Error__the_selected_file_is_not_found_ {
            get {
                return ResourceManager.GetString("Open_Error__the_selected_file_is_not_found_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap open_spec {
            get {
                object obj = ResourceManager.GetObject("open_spec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Verification Selected.
        /// </summary>
        internal static string Parallel_Verification_Selected {
            get {
                return ResourceManager.GetString("Parallel_Verification_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Verification UnSelected.
        /// </summary>
        internal static string Parallel_Verification_UnSelected {
            get {
                return ResourceManager.GetString("Parallel_Verification_UnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing error: .
        /// </summary>
        internal static string Parsing_error__ {
            get {
                return ResourceManager.GetString("Parsing_error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing error at line .
        /// </summary>
        internal static string Parsing_error_at_line_ {
            get {
                return ResourceManager.GetString("Parsing_error_at_line_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Order Reduction Selected.
        /// </summary>
        internal static string Partial_Order_Reduction_Selected {
            get {
                return ResourceManager.GetString("Partial_Order_Reduction_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Order Reduction UnSelected.
        /// </summary>
        internal static string Partial_Order_Reduction_UnSelected {
            get {
                return ResourceManager.GetString("Partial_Order_Reduction_UnSelected", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a model first!.
        /// </summary>
        internal static string Please_input_a_model_first_ {
            get {
                return ResourceManager.GetString("Please_input_a_model_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a valid output file!.
        /// </summary>
        internal static string Please_input_a_valid_output_file_ {
            get {
                return ResourceManager.GetString("Please_input_a_valid_output_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load a model first!.
        /// </summary>
        internal static string Please_load_a_model_first_ {
            get {
                return ResourceManager.GetString("Please_load_a_model_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that the format is correct!.
        /// </summary>
        internal static string Please_make_sure_that_the_format_is_correct_ {
            get {
                return ResourceManager.GetString("Please_make_sure_that_the_format_is_correct_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some input files!.
        /// </summary>
        internal static string Please_select_some_input_files_ {
            get {
                return ResourceManager.GetString("Please_select_some_input_files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop verification or simulation before parsing the model!.
        /// </summary>
        internal static string Please_stop_verification_or_simulation_before_parsing_the_model_ {
            get {
                return ResourceManager.GetString("Please_stop_verification_or_simulation_before_parsing_the_model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the verification to stop first! Otherwise it may cause exceptional behaviors..
        /// </summary>
        internal static string Please_wait_for_the_verification_to_stop_first__Otherwise_it_may_cause_exceptional_behaviors_ {
            get {
                return ResourceManager.GetString("Please_wait_for_the_verification_to_stop_first__Otherwise_it_may_cause_exceptiona" +
                        "l_behaviors_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Version.
        /// </summary>
        internal static string Registered_Version {
            get {
                return ResourceManager.GetString("Registered_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Generation Cancelled.
        /// </summary>
        internal static string Result_Generation_Cancelled {
            get {
                return ResourceManager.GetString("Result_Generation_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Exception Happened.
        /// </summary>
        internal static string Runtime_Exception_Happened {
            get {
                return ResourceManager.GetString("Runtime_Exception_Happened", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as {
            get {
                object obj = ResourceManager.GetObject("save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Output File.
        /// </summary>
        internal static string Save_Output_File {
            get {
                return ResourceManager.GetString("Save_Output_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving error.
        /// </summary>
        internal static string Saving_error {
            get {
                return ResourceManager.GetString("Saving_error", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap selection {
            get {
                object obj = ResourceManager.GetObject("selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest Witness Trace Selected.
        /// </summary>
        internal static string Shortest_Witness_Trace_Selected {
            get {
                return ResourceManager.GetString("Shortest_Witness_Trace_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest Witness Trace UnSelected.
        /// </summary>
        internal static string Shortest_Witness_Trace_UnSelected {
            get {
                return ResourceManager.GetString("Shortest_Witness_Trace_UnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification is parsed in {0}s.
        /// </summary>
        internal static string Specification_is_parsed_in__0_s {
            get {
                return ResourceManager.GetString("Specification_is_parsed_in__0_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Promela model is empty!.
        /// </summary>
        internal static string The_Promela_model_is_empty_ {
            get {
                return ResourceManager.GetString("The_Promela_model_is_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is read only. Do you want to overwrite it?.
        /// </summary>
        internal static string This_file_is_read_only__Do_you_want_to_overwrite_it_ {
            get {
                return ResourceManager.GetString("This_file_is_read_only__Do_you_want_to_overwrite_it_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose Mode Selected.
        /// </summary>
        internal static string Verbose_Mode_Selected {
            get {
                return ResourceManager.GetString("Verbose_Mode_Selected", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Verification {
            get {
                object obj = ResourceManager.GetObject("Verification", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Cancelled.
        /// </summary>
        internal static string Verification_Cancelled {
            get {
                return ResourceManager.GetString("Verification_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Completed.
        /// </summary>
        internal static string Verification_Completed {
            get {
                return ResourceManager.GetString("Verification_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification has been running for {0}s.
        /// </summary>
        internal static string Verification_has_been_running_for_ {
            get {
                return ResourceManager.GetString("Verification_has_been_running_for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Starts....
        /// </summary>
        internal static string Verification_Starts___ {
            get {
                return ResourceManager.GetString("Verification_Starts___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying Assertion: .
        /// </summary>
        internal static string Verifying_Assertion__ {
            get {
                return ResourceManager.GetString("Verifying_Assertion__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Expired.
        /// </summary>
        internal static string Version_Expired {
            get {
                return ResourceManager.GetString("Version_Expired", resourceCulture);
            }
        }
    }
}
